### ISSUE TITLE
Add a condition for staff users?

### ISSUE THREAD

**Issue by seralot** [cfpb/django-flags#107]
Hi,
If I'm not mistaken, you currently have a team of several people, and you want all of them to see the new feature flag. However, you need to add each user individually with the user condition. It might be worth considering adding a condition for staff users, similar to how it's currently done with anonymous users. This would make it easier to grant access to new features to staff members in the future. 

Is there a reason why not include this condition?

**Comment by willbarton** [comment]
> Is there a reason why not include this condition?

@seralot Nope, I saw your PR, and I think that makes sense as you described, but I'm not sure it needs to exist in django-flags itself.

You can include that condition in your own code and register it there, as described here: https://cfpb.github.io/django-flags/api/conditions/#registering-conditions

**Comment by seralot** [comment]
I see what you mean, and I agree that it's probably not necessary to have it in django-flags itself. I'll follow your advice and add the condition to my own code. Thanks @willbarton
