### ISSUE TITLE
Python 3.12 / Django 5 support on horizon?

### ISSUE THREAD

**Issue by striveforbest** [cfpb/django-flags#126]
Are you planning to keep working on the lib?  I noticed the latest versions of python/django are not supported.

**Comment by striveforbest** [comment]
I haven't tested it yet, according to your readme, it's:

```
    Python 3.7+
    Django 2.2-4.0
```

**Comment by willbarton** [comment]
I've merged #117 and updated the README (and various other packaging files) in #127. 

Django 5.0 and Python 3.12 support doesn't require a new release.
