### ISSUE TITLE
MiddlewareMixin requires Django 1.10

### ISSUE THREAD

**Issue by riceyrice** [cfpb/django-flags#43]
The readme claims Django 1.8 compatibility.
However version 4.0 adds `django.utils.deprecation.MiddlewareMixin` for Django 1.10 compatibility, which is not available in earlier versions of Django. 
https://github.com/cfpb/django-flags/blob/c56ff9a6ee5a8758095ac7c15fdffdd80b73c3af/flags/middleware.py#L8

I assume a ...
```
try: 
    from django.utils.deprecation import MiddlewareMixin
except ImportError:
    MiddlewareMixin = object
```
...will probably fix that, although right now I don't know if there are other incompatibilities.

**Comment by willbarton** [comment]
Hi @riceyrice! You're correct, unfortunately the README is wrong. [With 4.0.0 we dropped support for Django < 1.11](https://github.com/cfpb/django-flags/commit/96fc7f43b3faf3aaa9d14b2b19e50eb0daccaee6#diff-2eeaed663bd0d25b7e608891384b7298).

I've opened #44 to fix the README.
