### ISSUE TITLE
Release Python 3 support?

### ISSUE THREAD

**Issue by foogunlana** [cfpb/django-flags#63]
Less of an issue and more of a question. When is python 3 support going to be released please?

**Comment by willbarton** [comment]
@foogunlana Python 3.6+ has been supported for several years now. Django 3.0 support is in `master` and will be released very soon. I'd like to get #61 into that release.

I hope that answers your question!

**Comment by jcohen28** [comment]
hi @willbarton. thanks for maintaining this useful app! do you have an update on the timeline for releasing this Django 3.0 support?

**Comment by willbarton** [comment]
@jcohen28 @foogunlana Django-Flags 5.0.0 has been released with Django 3.0 support.
