### ISSUE TITLE
Install fails with Django 4.0.1

### ISSUE THREAD

**Issue by mdunc** [cfpb/django-flags#89]
Due to the `install_requires = ["Django>=1.11,<=4"]` constraint, only Django 4.0 is compatible and not the recent 4.0.1 patch.  Perhaps the `<=4` should just be dropped completely or changed to `<4.1` if there are concerns that 4.1 could break things?

**Comment by willbarton** [comment]
Thanks @mdunc. This has been fixed and I've released 5.0.7!
